name: Build Dist

on:
  push:
    branches:
      - main
      - update
    tags:
      - "*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set Env Vars
        run: |
          echo "DIST_ZIP_FILE=dist-${{ github.ref_name }}-`echo ${{ github.sha }} | cut -c1-7`.zip" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install package
        run: npm install
      - name: Make Dist
        run: npm run build-prod
      - name: Zip Dist
        run: zip -r ${{ env.DIST_ZIP_FILE }} dist
      - name: List Working Directory
        run: ls -la
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.DIST_ZIP_FILE }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
